In [2]:
import pandas as pd
import sqlalchemy as db
import cx_Oracle as orcl
import datetime as dt
import numpy as np
import psycopg2 
import seaborn as sns
import matplotlib.pyplot as plt
import math
import datetime as dt
%matplotlib inline
print("cx_Oracle.version:", orcl.version)
# show all columns without without truncating
pd.set_option('display.max_columns', None)

cx_Oracle.version: 7.3.0

In [3]:
conn = psycopg2.connect(host="128.2.1.25",database="datawarehouse", user="datawarehouse", password="P@ssw0rd")

In [4]:
customer = '''SELECT "public"."customers"."id" AS "id", "public"."customers"."firstname" AS "firstname", "public"."customers"."lastname" AS "lastname", "public"."customers"."branch" AS "branch", "public"."customers"."cust_id" AS "cust_id", "public"."customers"."dob" AS "dob", "public"."customers"."email" AS "email", "public"."customers"."gender" AS "gender", "public"."customers"."last_updated_date" AS "last_updated_date", "public"."customers"."middlename" AS "middlename", "public"."customers"."national_id" AS "national_id", "public"."customers"."open_date" AS "open_date", "public"."customers"."other_phone_numbers" AS "other_phone_numbers", "public"."customers"."phone_number" AS "phone_number", "public"."customers"."segment" AS "segment", "public"."customers"."status" AS "status", "public"."customers"."type" AS "type", "Accounts"."id" AS "id_2", "Accounts"."account_name" AS "account_name", "Accounts"."account_no" AS "account_no", "Accounts"."account_status" AS "account_status", "Accounts"."changed_by" AS "changed_by", "Accounts"."close_date" AS "close_date", "Accounts"."currency" AS "currency", "Accounts"."current_balance" AS "current_balance", "Accounts"."current_branch" AS "current_branch", "Accounts"."cust_id" AS "cust_id_2", "Accounts"."date_created" AS "date_created", "Accounts"."eom_date" AS "eom_date", "Accounts"."expiry_date" AS "expiry_date", "Accounts"."interest" AS "interest", "Accounts"."interest_end_date" AS "interest_end_date", "Accounts"."interest_rate" AS "interest_rate", "Accounts"."interest_start_date" AS "interest_start_date", "Accounts"."is_transacting_account" AS "is_transacting_account", "Accounts"."last_transaction_date" AS "last_transaction_date", "Accounts"."open_date" AS "open_date_2", "Accounts"."opened_by" AS "opened_by", "Accounts"."opening_branch" AS "opening_branch", "Accounts"."product_type" AS "product_type", "Accounts"."type" AS "type_2"
FROM "public"."customers"
LEFT JOIN "public"."accounts" "Accounts" ON "public"."customers"."cust_id" = "Accounts"."cust_id"
'''
customer = pd.read_sql_query(customer , conn)
customer

,id,firstname,lastname,branch,cust_id,dob,email,gender,last_updated_date,middlename,national_id,open_date,other_phone_numbers,phone_number,segment,status,type,id_2,account_name,account_no,account_status,changed_by,close_date,currency,current_balance,current_branch,cust_id_2,date_created,eom_date,expiry_date,interest,interest_end_date,interest_rate,interest_start_date,is_transacting_account,last_transaction_date,open_date_2,opened_by,opening_branch,product_type,type_2
0,28385,TAMERA,ADHIAMBO ...,KISUMU,158721,2000-05-28 00:00:00+03:00,...,F,0001-01-01 00:00:00+02:27,,00411105982,2016-01-01 00:00:00+03:00,,,MASS,1,1,33715207.0,TAMERA ADHIAMBO,2000101532,ACTIVE,None,2001-01-01,KES,129124.52,KISUMU,158721.0,2020-03-03 07:01:37.272010,2020-03-02,2001-01-01,546.84,2001-01-01,0.0,2001-01-01,True,2019-08-29,2014-02-26,GOA1984,KISUMU,TREASURE SAVINGS ACCOUNT,TREASURE SAVINGS ACCOUNT
1,28368,DAVID,MACHIRI ...,ELDORET,158692,1984-06-14 00:00:00+03:00,...,M,0001-01-01 00:00:00+02:27,NJENGA,23650419,2016-01-01 00:00:00+03:00,,254750679969,MASS,1,1,33980278.0,DAVID MACHIRI,7190009942,ACTIVE,None,2001-01-01,KES,0.00,ELDORET,158692.0,2020-03-03 07:02:10.064323,2020-03-02,2001-01-01,0.00,2001-01-01,0.0,2001-01-01,True,NaT,2014-02-26,None,ELDORET,TRANSACTIONAL ACCOUNT-CA,TRANSACTIONAL ACCOUNT-CA
2,29385,JUDY,KIPROP ...,ELDORET,159661,1984-01-10 00:00:00+03:00,...,F,0001-01-01 00:00:00+02:27,JEPKECH,24420197,2016-01-01 00:00:00+03:00,,254727566455,MASS,1,1,33331769.0,JUDY KIPROP,2000101823,DORMANT,None,2001-01-01,KES,570.13,ELDORET,159661.0,2020-03-03 07:00:46.481682,2020-03-02,2001-01-01,0.00,2001-01-01,0.0,2001-01-01,True,2014-07-09,2014-03-11,None,ELDORET,CROSS OVER SAVING ACCOUNT,CROSS OVER SAVING ACCOUNT
3,29914,MWANGI,MUCHIRO ...,REHANI,16016,1901-01-01 00:00:00+02:27,...,M,0001-01-01 00:00:00+02:27,,0000,2016-01-01 00:00:00+03:00,,,MASS,1,1,33576708.0,MWANGI MUCHIRO,2000012062,BLOCKED,None,2001-01-01,KES,17778.15,REHANI,16016.0,2020-03-03 07:01:18.489724,2020-03-02,2001-01-01,0.00,2001-01-01,0.0,2001-01-01,True,2015-06-04,1998-11-23,ENN1318,REHANI,TRANSACTIONAL ACCOUNT-CA,TRANSACTIONAL ACCOUNT-CA
4,29992,ERIC,KIRAGU ...,WESTLANDS,160207,1988-04-08 00:00:00+03:00,ERIQUEMWAS@GMAIL.COM ...,M,2018-07-18 00:00:00+03:00,MWANGI,25776364,2016-01-01 00:00:00+03:00,,,MASS,1,1,34142106.0,ERIC KIRAGU,2000108493,DORMANT,None,2001-01-01,KES,194.44,WESTLANDS,160207.0,2020-03-03 07:02:29.901520,2020-03-02,2001-01-01,0.00,2001-01-01,0.0,2001-01-01,True,2017-08-17,2015-01-23,EWK1231,WESTLANDS,CROSS OVER SAVING ACCOUNT,CROSS OVER SAVING ACCOUNT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825344,70509,PAUL,NJUGUNA ...,REHANI,59139,1983-01-11 00:00:00+03:00,PNJUGUNA17@GMAIL.COM ...,M,2018-06-05 00:00:00+03:00,NGUGI,22545233,2016-01-01 00:00:00+03:00,,254725725265,MASS,1,1,34149129.0,PAUL NJUGUNA,7500003194,ACTIVE,None,2001-01-01,KES,83.31,REHANI,59139.0,2020-03-03 07:02:30.634327,2020-03-02,2001-01-01,0.00,2001-01-01,0.0,2001-01-01,True,2017-04-12,2014-10-24,None,HEAD OFFICE,TAKE ON ACCOUNT,TAKE ON ACCOUNT
825345,70722,SARAH,ROTICH ...,HF WHIZZ,263501,1992-10-01 00:00:00+03:00,...,F,0001-01-01 00:00:00+02:27,CHEROP,30131476,2018-08-03 00:00:00+03:00,,254717079758,VIRTUAL,1,1,33784729.0,SARAH ROTICH,2635013201,ACTIVE,None,2001-01-01,KES,0.00,HF WHIZZ,263501.0,2020-03-03 07:01:46.239880,2020-03-02,2001-01-01,0.00,2001-01-01,0.0,2001-01-01,False,2001-01-01,2018-08-03,1SALESMAN,HF WHIZZ,VIRTUAL ACCOUNT MOBILE,VIRTUAL ACCOUNT MOBILE
825346,71910,JANE,MUGO ...,HF WHIZZ,264069,1973-01-01 00:00:00+03:00,...,F,0001-01-01 00:00:00+02:27,WANJIKU,13032170,2018-08-03 00:00:00+03:00,,254723923892,VIRTUAL,1,1,33635850.0,JANE MUGO,2640693201,ACTIVE,None,2001-01-01,KES,0.00,HF WHIZZ,264069.0,2020-03-03 07:01:26.427310,2020-03-02,2001-01-01,0.00,2001-01-01,0.0,2001-01-01,False,2001-01-01,2018-08-03,1SALESMAN,HF WHIZZ,VIRTUAL ACCOUNT MOBILE,VIRTUAL ACCOUNT MOBILE
825347,72345,KENYUA,NGUNJIRI ...,REHANI,64590,1941-10-23 00:00:00+02:45,...,M,2019-12-24 00:00:00+03:00,,11350454,2016-01-01 00:00:00+03:00,,254722529341,STANDARD,1,1,33804449.0,KENYUA NGUNJIRI,2000018565,ACTIVE,None,2001-01-01,KES,1311748.04,REHANI,64590.0,2020-03-03 07:01:48.451019,2020-03-02,2001-01-01,0.00,2001-01-01,0.0,2001-01-01,True,2020-03-02,1998-11-23,None,REHANI,LENGO ACCOUNT,LENGO ACCOUNT
825348,72895,GEORGE,CHECHE ...,HF WHIZZ,264560,1996-09-21 00:00:00+03:00,...,M,0001-01-01 00:00:00+02:27,SAITOTI,33544757,2018-08-04 00:00:00+03:00,,254702060116,VIRTUAL,1,1,33383881.0,GEORGE CHECHE,2645603201,DORMANT,None,2001-01-01,KES,4.00,HF WHIZZ,264560.0,2020-03-03 07:00:52.887816,2020-03-02,2001-01-01,0.00,2001-01-01,0.0,2001-01-01,True,2018-08-08,2018-08-04,1SALESMAN,HF WHIZZ,VIRTUAL ACCOUNT MOBILE,VIRTUAL ACCOUNT MOBILE

In [ ]:
customer.query()